#!/usr/bin/env bash
# conf load balancer server

config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend myweb
    
backend myweb
    balance roundrobin
    server 484792-web-01 100.25.134.17:80 check
    server 484792-web-02 54.84.167.34:80 check
"
apt-get -y update
apt-get -y upgrade

# Add HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# Install HAProxy
apt-get -y install haproxy

#copy original conf
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
