#!/usr/bin/env bash
# Set nginx to run as nginx user

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

# Configure nginx to listen on all active IPs on port 8080
sed -i 's/^listen  .*:80;/listen  *:8080;/g' /etc/nginx/sites-available/default

sudo service nginx restart
